export const APP_NAME = 'DDashBoard'
export const APP_SHORT_NAME = 'DDash'
export const APP_SECONDARY_NAME = 'Board'
export const APP_DESCRIPTION = 'DDNet community platform'
export const BASE_URL = process.env.NEXT_PUBLIC_SERVER_URL || 'https://ddashboard.gg'
