services:
  web:
    image: pippsza/ddnet-web:latest
    ports:
      - "4200:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - BOT_DOCKER_IMAGE=pippsza/ddnet-bot:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
