/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    bingo: Bingo;
    races: Race;
    bots: Bot;
    notifications: Notification;
    'friend-requests': FriendRequest;
    articles: Article;
    'forum-posts': ForumPost;
    support: Support;
    'verification-requests': VerificationRequest;
    'chat-sessions': ChatSession;
    'push-subscriptions': PushSubscription;
    conversations: Conversation;
    messages: Message;
    'in-game-messages': InGameMessage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    bingo: BingoSelect<false> | BingoSelect<true>;
    races: RacesSelect<false> | RacesSelect<true>;
    bots: BotsSelect<false> | BotsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'friend-requests': FriendRequestsSelect<false> | FriendRequestsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'forum-posts': ForumPostsSelect<false> | ForumPostsSelect<true>;
    support: SupportSelect<false> | SupportSelect<true>;
    'verification-requests': VerificationRequestsSelect<false> | VerificationRequestsSelect<true>;
    'chat-sessions': ChatSessionsSelect<false> | ChatSessionsSelect<true>;
    'push-subscriptions': PushSubscriptionsSelect<false> | PushSubscriptionsSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'in-game-messages': InGameMessagesSelect<false> | InGameMessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'verification-settings': VerificationSetting;
    'custom-categories': CustomCategory;
  };
  globalsSelect: {
    'verification-settings': VerificationSettingsSelect<false> | VerificationSettingsSelect<true>;
    'custom-categories': CustomCategoriesSelect<false> | CustomCategoriesSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Case-sensitive DDNet nickname for verification and display
   */
  ingameNick: string;
  roles: 'admin' | 'player' | 'moderator' | 'tester';
  isSystemVerified?: boolean | null;
  lastSeenAt?: string | null;
  avatar?: (string | null) | Media;
  friend?:
    | {
        user: string | User;
        addedAt: string;
        nickname?: string | null;
        id?: string | null;
      }[]
    | null;
  ingameStats?: {
    points?: number | null;
    /**
     * Global completionist rank from DDNet
     */
    rank?: number | null;
    skin?: {
      name?: string | null;
      color_body?: number | null;
      color_feet?: number | null;
    };
    /**
     * Last time DDNet stats were synced
     */
    lastSyncedAt?: string | null;
  };
  /**
   * Current game (bingo or race) with status "waiting", "ready" or "in_progress"
   */
  activeGame?:
    | ({
        relationTo: 'bingo';
        value: string | Bingo;
      } | null)
    | ({
        relationTo: 'races';
        value: string | Race;
      } | null);
  /**
   * History of all played games (bingo and races)
   */
  completedGames?:
    | (
        | {
            relationTo: 'bingo';
            value: string | Bingo;
          }
        | {
            relationTo: 'races';
            value: string | Race;
          }
      )[]
    | null;
  bingo?: {
    novice?: {
      solo?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalMapsCompleted?: number | null;
        averageGameDuration?: number | null;
        fastestWin?: number | null;
      };
      team?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalMapsCompleted?: number | null;
        averageGameDuration?: number | null;
        fastestWin?: number | null;
      };
    };
    moderate?: {
      solo?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalMapsCompleted?: number | null;
        averageGameDuration?: number | null;
        fastestWin?: number | null;
      };
      team?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalMapsCompleted?: number | null;
        averageGameDuration?: number | null;
        fastestWin?: number | null;
      };
    };
    brutal?: {
      solo?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalMapsCompleted?: number | null;
        averageGameDuration?: number | null;
        fastestWin?: number | null;
      };
      team?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalMapsCompleted?: number | null;
        averageGameDuration?: number | null;
        fastestWin?: number | null;
      };
    };
    insane?: {
      solo?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalMapsCompleted?: number | null;
        averageGameDuration?: number | null;
        fastestWin?: number | null;
      };
      team?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalMapsCompleted?: number | null;
        averageGameDuration?: number | null;
        fastestWin?: number | null;
      };
    };
    dummy?: {
      solo?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalMapsCompleted?: number | null;
        averageGameDuration?: number | null;
        fastestWin?: number | null;
      };
      team?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalMapsCompleted?: number | null;
        averageGameDuration?: number | null;
        fastestWin?: number | null;
      };
    };
    ddmax?: {
      easy?: {
        solo?: {
          gamesPlayed?: number | null;
          gamesWon?: number | null;
          gamesLost?: number | null;
          totalMapsCompleted?: number | null;
          averageGameDuration?: number | null;
          fastestWin?: number | null;
        };
        team?: {
          gamesPlayed?: number | null;
          gamesWon?: number | null;
          gamesLost?: number | null;
          totalMapsCompleted?: number | null;
          averageGameDuration?: number | null;
          fastestWin?: number | null;
        };
      };
      next?: {
        solo?: {
          gamesPlayed?: number | null;
          gamesWon?: number | null;
          gamesLost?: number | null;
          totalMapsCompleted?: number | null;
          averageGameDuration?: number | null;
          fastestWin?: number | null;
        };
        team?: {
          gamesPlayed?: number | null;
          gamesWon?: number | null;
          gamesLost?: number | null;
          totalMapsCompleted?: number | null;
          averageGameDuration?: number | null;
          fastestWin?: number | null;
        };
      };
      pro?: {
        solo?: {
          gamesPlayed?: number | null;
          gamesWon?: number | null;
          gamesLost?: number | null;
          totalMapsCompleted?: number | null;
          averageGameDuration?: number | null;
          fastestWin?: number | null;
        };
        team?: {
          gamesPlayed?: number | null;
          gamesWon?: number | null;
          gamesLost?: number | null;
          totalMapsCompleted?: number | null;
          averageGameDuration?: number | null;
          fastestWin?: number | null;
        };
      };
      nut?: {
        solo?: {
          gamesPlayed?: number | null;
          gamesWon?: number | null;
          gamesLost?: number | null;
          totalMapsCompleted?: number | null;
          averageGameDuration?: number | null;
          fastestWin?: number | null;
        };
        team?: {
          gamesPlayed?: number | null;
          gamesWon?: number | null;
          gamesLost?: number | null;
          totalMapsCompleted?: number | null;
          averageGameDuration?: number | null;
          fastestWin?: number | null;
        };
      };
    };
    oldschool?: {
      solo?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalMapsCompleted?: number | null;
        averageGameDuration?: number | null;
        fastestWin?: number | null;
      };
      team?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalMapsCompleted?: number | null;
        averageGameDuration?: number | null;
        fastestWin?: number | null;
      };
    };
    solo_maps?: {
      solo?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalMapsCompleted?: number | null;
        averageGameDuration?: number | null;
        fastestWin?: number | null;
      };
    };
    race?: {
      solo?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalMapsCompleted?: number | null;
        averageGameDuration?: number | null;
        fastestWin?: number | null;
      };
    };
    /**
     * Calculated automatically
     */
    totalGamesPlayed?: number | null;
    /**
     * Calculated automatically
     */
    totalGamesWon?: number | null;
    /**
     * Calculated automatically (totalWins / totalPlayed * 100)
     */
    winRate?: number | null;
    /**
     * Automatically determined by most played category
     */
    favoriteCategory?: string | null;
  };
  raceStats?: {
    novice?: {
      gamesPlayed?: number | null;
      gamesWon?: number | null;
      gamesLost?: number | null;
      totalRoundsWon?: number | null;
      /**
       * Best round finish time in seconds
       */
      bestFinishTime?: number | null;
      averageFinishTime?: number | null;
    };
    moderate?: {
      gamesPlayed?: number | null;
      gamesWon?: number | null;
      gamesLost?: number | null;
      totalRoundsWon?: number | null;
      /**
       * Best round finish time in seconds
       */
      bestFinishTime?: number | null;
      averageFinishTime?: number | null;
    };
    brutal?: {
      gamesPlayed?: number | null;
      gamesWon?: number | null;
      gamesLost?: number | null;
      totalRoundsWon?: number | null;
      /**
       * Best round finish time in seconds
       */
      bestFinishTime?: number | null;
      averageFinishTime?: number | null;
    };
    insane?: {
      gamesPlayed?: number | null;
      gamesWon?: number | null;
      gamesLost?: number | null;
      totalRoundsWon?: number | null;
      /**
       * Best round finish time in seconds
       */
      bestFinishTime?: number | null;
      averageFinishTime?: number | null;
    };
    dummy?: {
      gamesPlayed?: number | null;
      gamesWon?: number | null;
      gamesLost?: number | null;
      totalRoundsWon?: number | null;
      /**
       * Best round finish time in seconds
       */
      bestFinishTime?: number | null;
      averageFinishTime?: number | null;
    };
    ddmax?: {
      easy?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalRoundsWon?: number | null;
        /**
         * Best round finish time in seconds
         */
        bestFinishTime?: number | null;
        averageFinishTime?: number | null;
      };
      next?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalRoundsWon?: number | null;
        /**
         * Best round finish time in seconds
         */
        bestFinishTime?: number | null;
        averageFinishTime?: number | null;
      };
      pro?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalRoundsWon?: number | null;
        /**
         * Best round finish time in seconds
         */
        bestFinishTime?: number | null;
        averageFinishTime?: number | null;
      };
      nut?: {
        gamesPlayed?: number | null;
        gamesWon?: number | null;
        gamesLost?: number | null;
        totalRoundsWon?: number | null;
        /**
         * Best round finish time in seconds
         */
        bestFinishTime?: number | null;
        averageFinishTime?: number | null;
      };
    };
    oldschool?: {
      gamesPlayed?: number | null;
      gamesWon?: number | null;
      gamesLost?: number | null;
      totalRoundsWon?: number | null;
      /**
       * Best round finish time in seconds
       */
      bestFinishTime?: number | null;
      averageFinishTime?: number | null;
    };
    solo_maps?: {
      gamesPlayed?: number | null;
      gamesWon?: number | null;
      gamesLost?: number | null;
      totalRoundsWon?: number | null;
      /**
       * Best round finish time in seconds
       */
      bestFinishTime?: number | null;
      averageFinishTime?: number | null;
    };
    race?: {
      gamesPlayed?: number | null;
      gamesWon?: number | null;
      gamesLost?: number | null;
      totalRoundsWon?: number | null;
      /**
       * Best round finish time in seconds
       */
      bestFinishTime?: number | null;
      averageFinishTime?: number | null;
    };
    /**
     * Calculated automatically
     */
    totalRacesPlayed?: number | null;
    /**
     * Calculated automatically
     */
    totalRacesWon?: number | null;
    /**
     * Calculated automatically
     */
    winRate?: number | null;
    /**
     * Automatically determined by most played category
     */
    favoriteCategory?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email?: string | null;
  /**
   * Lowercase login name (auto-set by Payload)
   */
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bingo".
 */
export interface Bingo {
  id: string;
  title: string;
  mode: 'solo' | 'team';
  category: string;
  /**
   * Available for DDmaX and Oldschool categories
   */
  subcategory?: ('ddmax_easy' | 'ddmax_next' | 'ddmax_pro' | 'ddmax_nut') | null;
  gridSize: '3x3' | '5x5' | '7x7';
  winCondition: 'line' | 'cross' | 'full_house';
  /**
   * Public games are visible in lobby, private games require invite code
   */
  isPublic?: boolean | null;
  difficultyRange?: {
    min?: number | null;
    max?: number | null;
  };
  createdBy: string | User;
  /**
   * Auto-generated code for private games. Share this link: /bingo/join/{code}
   */
  inviteCode?: string | null;
  maps: {
    mapName: string;
    position: number;
    id?: string | null;
  }[];
  /**
   * Solo mode: 1 team (1-2 players), Team mode: 2 teams (1-2 players each)
   */
  teams: {
    teamName: string;
    color: 'red' | 'blue' | 'green' | 'yellow' | 'purple' | 'orange';
    /**
     * Each team must have 1-2 players. Only players in team receive tokens.
     */
    players: {
      user: string | User;
      isReady?: boolean | null;
      id?: string | null;
    }[];
    /**
     * Array of cell positions that this team has completed
     */
    completedCells?:
      | {
          cellPosition: number;
          completedAt?: string | null;
          id?: string | null;
        }[]
      | null;
    teamStatus: 'not_ready' | 'ready' | 'playing' | 'winner' | 'loser';
    id?: string | null;
  }[];
  gameStatus: 'waiting' | 'ready' | 'in_progress' | 'completed' | 'cancelled';
  /**
   * Index of winning team (0 or 1) - only for team mode with 2 teams
   */
  winnerTeam?: number | null;
  startedAt?: string | null;
  completedAt?: string | null;
  /**
   * Calculated automatically
   */
  duration?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Race game sessions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "races".
 */
export interface Race {
  id: string;
  title: string;
  /**
   * If enabled, this race will be visible in the public lobby
   */
  isPublic?: boolean | null;
  /**
   * Code for joining private games
   */
  inviteCode?: string | null;
  category: string;
  totalRounds: number;
  currentRound?: number | null;
  currentMap?: string | null;
  server: {
    ip: string;
    port: number;
    name?: string | null;
  };
  players: {
    user: string | User;
    ingameNick: string;
    roundsWon?: number | null;
    isReady?: boolean | null;
    id?: string | null;
  }[];
  rounds?:
    | {
        roundNumber: number;
        mapName: string;
        winner?: (string | null) | User;
        finishTime?: number | null;
        completedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  winner?: (string | null) | User;
  status: 'waiting' | 'ready' | 'in_progress' | 'completed' | 'cancelled';
  /**
   * ID of the bot monitoring this race
   */
  botId?: string | null;
  createdBy: string | User;
  startedAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage running bot instances
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bots".
 */
export interface Bot {
  id: string;
  /**
   * Human-readable name for this bot instance
   */
  name: string;
  /**
   * Docker container ID for this bot
   */
  containerId: string;
  /**
   * The mode this bot is running in
   */
  mode: 'verification' | 'race' | 'chat' | 'monitor';
  /**
   * Current status of the bot
   */
  status: 'starting' | 'running' | 'stopping' | 'stopped' | 'error';
  /**
   * The server this bot is connected to
   */
  connectedServer?: {
    ip?: string | null;
    port?: number | null;
    name?: string | null;
  };
  /**
   * The game this bot is associated with (if any)
   */
  linkedGame?:
    | ({
        relationTo: 'bingo';
        value: string | Bingo;
      } | null)
    | ({
        relationTo: 'races';
        value: string | Race;
      } | null);
  /**
   * The user who initiated this bot (if any)
   */
  linkedUser?: (string | null) | User;
  /**
   * Recent log entries from the bot
   */
  logs?:
    | {
        timestamp: string;
        level?: ('info' | 'warn' | 'error') | null;
        message: string;
        id?: string | null;
      }[]
    | null;
  startedAt?: string | null;
  stoppedAt?: string | null;
  /**
   * Additional data specific to the bot mode
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * In-app notifications for users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  /**
   * The user who will receive this notification
   */
  recipient: string | User;
  /**
   * Type of notification
   */
  type:
    | 'game_invite'
    | 'friend_request'
    | 'friend_accepted'
    | 'game_started'
    | 'game_ended'
    | 'round_won'
    | 'achievement'
    | 'system';
  title: string;
  message: string;
  isRead?: boolean | null;
  /**
   * URL to navigate to when clicking the notification
   */
  actionUrl?: string | null;
  /**
   * The game this notification is about (if any)
   */
  relatedGame?:
    | ({
        relationTo: 'bingo';
        value: string | Bingo;
      } | null)
    | ({
        relationTo: 'races';
        value: string | Race;
      } | null);
  /**
   * The user who triggered this notification (if any)
   */
  relatedUser?: (string | null) | User;
  /**
   * Extra data for custom notification handling
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Friend request management
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "friend-requests".
 */
export interface FriendRequest {
  id: string;
  /**
   * User who sent the friend request
   */
  sender: string | User;
  /**
   * User who received the friend request
   */
  recipient: string | User;
  status: 'pending' | 'accepted' | 'rejected';
  /**
   * Optional message from sender
   */
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  title: string;
  /**
   * URL-friendly version of the title
   */
  slug: string;
  /**
   * Short description for preview and SEO
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (string | null) | Media;
  /**
   * Article author
   */
  author: string | User;
  category?: ('news' | 'tutorial' | 'guide' | 'update' | 'event' | 'announcement') | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Show this article in featured section
   */
  featured?: boolean | null;
  views?: number | null;
  likes?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-posts".
 */
export interface ForumPost {
  id: string;
  title: string;
  /**
   * URL-friendly version of the title
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Post author
   */
  author: string | User;
  category: 'general' | 'help' | 'suggestions' | 'bugs' | 'maps' | 'clans' | 'offtopic';
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Locked posts cannot be edited or have new replies
   */
  status: 'published' | 'hidden' | 'locked';
  /**
   * Only admins/moderators can pin posts
   */
  isPinned?: boolean | null;
  views?: number | null;
  likes?: number | null;
  replies?:
    | {
        author: string | User;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        createdAt: string;
        likes?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support".
 */
export interface Support {
  id: string;
  /**
   * Brief description of the issue
   */
  subject: string;
  category:
    | 'name_change'
    | 'bug_report'
    | 'nickname_conflict'
    | 'account_issues'
    | 'game_statistics'
    | 'verification_request'
    | 'other';
  /**
   * Priority level of the ticket
   */
  priority: 'low' | 'medium' | 'high' | 'critical';
  status: 'open' | 'in_progress' | 'waiting_for_user' | 'resolved' | 'closed' | 'rejected';
  /**
   * Detailed description of the issue
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * User who created this ticket (empty for anonymous)
   */
  createdBy?: (string | null) | User;
  /**
   * Email for anonymous ticket submissions
   */
  contactEmail?: string | null;
  /**
   * Communication thread between user and support
   */
  responses?:
    | {
        message: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        author: string | User;
        /**
         * Response from admin or moderator
         */
        isStaffResponse?: boolean | null;
        timestamp: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Files attached to this ticket (screenshots, logs, etc.)
   */
  attachments?:
    | {
        file: string | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Additional information for specific ticket types
   */
  metadata?: {
    /**
     * For name change requests
     */
    requestedName?: string | null;
    /**
     * For nickname conflict tickets
     */
    conflictingUser?: (string | null) | User;
  };
  /**
   * Timestamp when ticket was resolved
   */
  resolvedAt?: string | null;
  /**
   * Internal notes about how the ticket was resolved
   */
  resolutionNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-requests".
 */
export interface VerificationRequest {
  id: string;
  /**
   * The in-game nickname to verify
   */
  nickname: string;
  status: 'pending' | 'success' | 'expired' | 'failed';
  /**
   * Reason for failure (not_logged_in, not_found, error details)
   */
  message?: string | null;
  /**
   * IP:Port where the bot checked the player
   */
  currentServer?: string | null;
  /**
   * Docker container ID running the bot
   */
  containerId?: string | null;
  user: string | User;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * In-game chat sessions between users via bot relay
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-sessions".
 */
export interface ChatSession {
  id: string;
  initiator: string | User;
  target: string | User;
  targetNickname: string;
  status?: ('connecting' | 'active' | 'disconnected' | 'error') | null;
  server?: {
    ip?: string | null;
    port?: number | null;
    name?: string | null;
  };
  botContainerId?: string | null;
  startedAt?: string | null;
  endedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * PWA push notification subscriptions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions".
 */
export interface PushSubscription {
  id: string;
  user: string | User;
  endpoint: string;
  p256dh: string;
  auth: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: string;
  participants: {
    user: string | User;
    id?: string | null;
  }[];
  lastMessage?: string | null;
  lastMessageAt?: string | null;
  lastMessageBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  conversation: string | Conversation;
  sender: string | User;
  content: string;
  isRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Archived messages from in-game chat sessions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "in-game-messages".
 */
export interface InGameMessage {
  id: string;
  session: string | ChatSession;
  sender: 'user' | 'friend' | 'system';
  content: string;
  timestamp: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'bingo';
        value: string | Bingo;
      } | null)
    | ({
        relationTo: 'races';
        value: string | Race;
      } | null)
    | ({
        relationTo: 'bots';
        value: string | Bot;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'friend-requests';
        value: string | FriendRequest;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'forum-posts';
        value: string | ForumPost;
      } | null)
    | ({
        relationTo: 'support';
        value: string | Support;
      } | null)
    | ({
        relationTo: 'verification-requests';
        value: string | VerificationRequest;
      } | null)
    | ({
        relationTo: 'chat-sessions';
        value: string | ChatSession;
      } | null)
    | ({
        relationTo: 'push-subscriptions';
        value: string | PushSubscription;
      } | null)
    | ({
        relationTo: 'conversations';
        value: string | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'in-game-messages';
        value: string | InGameMessage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  ingameNick?: T;
  roles?: T;
  isSystemVerified?: T;
  lastSeenAt?: T;
  avatar?: T;
  friend?:
    | T
    | {
        user?: T;
        addedAt?: T;
        nickname?: T;
        id?: T;
      };
  ingameStats?:
    | T
    | {
        points?: T;
        rank?: T;
        skin?:
          | T
          | {
              name?: T;
              color_body?: T;
              color_feet?: T;
            };
        lastSyncedAt?: T;
      };
  activeGame?: T;
  completedGames?: T;
  bingo?:
    | T
    | {
        novice?:
          | T
          | {
              solo?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalMapsCompleted?: T;
                    averageGameDuration?: T;
                    fastestWin?: T;
                  };
              team?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalMapsCompleted?: T;
                    averageGameDuration?: T;
                    fastestWin?: T;
                  };
            };
        moderate?:
          | T
          | {
              solo?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalMapsCompleted?: T;
                    averageGameDuration?: T;
                    fastestWin?: T;
                  };
              team?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalMapsCompleted?: T;
                    averageGameDuration?: T;
                    fastestWin?: T;
                  };
            };
        brutal?:
          | T
          | {
              solo?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalMapsCompleted?: T;
                    averageGameDuration?: T;
                    fastestWin?: T;
                  };
              team?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalMapsCompleted?: T;
                    averageGameDuration?: T;
                    fastestWin?: T;
                  };
            };
        insane?:
          | T
          | {
              solo?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalMapsCompleted?: T;
                    averageGameDuration?: T;
                    fastestWin?: T;
                  };
              team?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalMapsCompleted?: T;
                    averageGameDuration?: T;
                    fastestWin?: T;
                  };
            };
        dummy?:
          | T
          | {
              solo?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalMapsCompleted?: T;
                    averageGameDuration?: T;
                    fastestWin?: T;
                  };
              team?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalMapsCompleted?: T;
                    averageGameDuration?: T;
                    fastestWin?: T;
                  };
            };
        ddmax?:
          | T
          | {
              easy?:
                | T
                | {
                    solo?:
                      | T
                      | {
                          gamesPlayed?: T;
                          gamesWon?: T;
                          gamesLost?: T;
                          totalMapsCompleted?: T;
                          averageGameDuration?: T;
                          fastestWin?: T;
                        };
                    team?:
                      | T
                      | {
                          gamesPlayed?: T;
                          gamesWon?: T;
                          gamesLost?: T;
                          totalMapsCompleted?: T;
                          averageGameDuration?: T;
                          fastestWin?: T;
                        };
                  };
              next?:
                | T
                | {
                    solo?:
                      | T
                      | {
                          gamesPlayed?: T;
                          gamesWon?: T;
                          gamesLost?: T;
                          totalMapsCompleted?: T;
                          averageGameDuration?: T;
                          fastestWin?: T;
                        };
                    team?:
                      | T
                      | {
                          gamesPlayed?: T;
                          gamesWon?: T;
                          gamesLost?: T;
                          totalMapsCompleted?: T;
                          averageGameDuration?: T;
                          fastestWin?: T;
                        };
                  };
              pro?:
                | T
                | {
                    solo?:
                      | T
                      | {
                          gamesPlayed?: T;
                          gamesWon?: T;
                          gamesLost?: T;
                          totalMapsCompleted?: T;
                          averageGameDuration?: T;
                          fastestWin?: T;
                        };
                    team?:
                      | T
                      | {
                          gamesPlayed?: T;
                          gamesWon?: T;
                          gamesLost?: T;
                          totalMapsCompleted?: T;
                          averageGameDuration?: T;
                          fastestWin?: T;
                        };
                  };
              nut?:
                | T
                | {
                    solo?:
                      | T
                      | {
                          gamesPlayed?: T;
                          gamesWon?: T;
                          gamesLost?: T;
                          totalMapsCompleted?: T;
                          averageGameDuration?: T;
                          fastestWin?: T;
                        };
                    team?:
                      | T
                      | {
                          gamesPlayed?: T;
                          gamesWon?: T;
                          gamesLost?: T;
                          totalMapsCompleted?: T;
                          averageGameDuration?: T;
                          fastestWin?: T;
                        };
                  };
            };
        oldschool?:
          | T
          | {
              solo?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalMapsCompleted?: T;
                    averageGameDuration?: T;
                    fastestWin?: T;
                  };
              team?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalMapsCompleted?: T;
                    averageGameDuration?: T;
                    fastestWin?: T;
                  };
            };
        solo_maps?:
          | T
          | {
              solo?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalMapsCompleted?: T;
                    averageGameDuration?: T;
                    fastestWin?: T;
                  };
            };
        race?:
          | T
          | {
              solo?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalMapsCompleted?: T;
                    averageGameDuration?: T;
                    fastestWin?: T;
                  };
            };
        totalGamesPlayed?: T;
        totalGamesWon?: T;
        winRate?: T;
        favoriteCategory?: T;
      };
  raceStats?:
    | T
    | {
        novice?:
          | T
          | {
              gamesPlayed?: T;
              gamesWon?: T;
              gamesLost?: T;
              totalRoundsWon?: T;
              bestFinishTime?: T;
              averageFinishTime?: T;
            };
        moderate?:
          | T
          | {
              gamesPlayed?: T;
              gamesWon?: T;
              gamesLost?: T;
              totalRoundsWon?: T;
              bestFinishTime?: T;
              averageFinishTime?: T;
            };
        brutal?:
          | T
          | {
              gamesPlayed?: T;
              gamesWon?: T;
              gamesLost?: T;
              totalRoundsWon?: T;
              bestFinishTime?: T;
              averageFinishTime?: T;
            };
        insane?:
          | T
          | {
              gamesPlayed?: T;
              gamesWon?: T;
              gamesLost?: T;
              totalRoundsWon?: T;
              bestFinishTime?: T;
              averageFinishTime?: T;
            };
        dummy?:
          | T
          | {
              gamesPlayed?: T;
              gamesWon?: T;
              gamesLost?: T;
              totalRoundsWon?: T;
              bestFinishTime?: T;
              averageFinishTime?: T;
            };
        ddmax?:
          | T
          | {
              easy?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalRoundsWon?: T;
                    bestFinishTime?: T;
                    averageFinishTime?: T;
                  };
              next?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalRoundsWon?: T;
                    bestFinishTime?: T;
                    averageFinishTime?: T;
                  };
              pro?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalRoundsWon?: T;
                    bestFinishTime?: T;
                    averageFinishTime?: T;
                  };
              nut?:
                | T
                | {
                    gamesPlayed?: T;
                    gamesWon?: T;
                    gamesLost?: T;
                    totalRoundsWon?: T;
                    bestFinishTime?: T;
                    averageFinishTime?: T;
                  };
            };
        oldschool?:
          | T
          | {
              gamesPlayed?: T;
              gamesWon?: T;
              gamesLost?: T;
              totalRoundsWon?: T;
              bestFinishTime?: T;
              averageFinishTime?: T;
            };
        solo_maps?:
          | T
          | {
              gamesPlayed?: T;
              gamesWon?: T;
              gamesLost?: T;
              totalRoundsWon?: T;
              bestFinishTime?: T;
              averageFinishTime?: T;
            };
        race?:
          | T
          | {
              gamesPlayed?: T;
              gamesWon?: T;
              gamesLost?: T;
              totalRoundsWon?: T;
              bestFinishTime?: T;
              averageFinishTime?: T;
            };
        totalRacesPlayed?: T;
        totalRacesWon?: T;
        winRate?: T;
        favoriteCategory?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bingo_select".
 */
export interface BingoSelect<T extends boolean = true> {
  title?: T;
  mode?: T;
  category?: T;
  subcategory?: T;
  gridSize?: T;
  winCondition?: T;
  isPublic?: T;
  difficultyRange?:
    | T
    | {
        min?: T;
        max?: T;
      };
  createdBy?: T;
  inviteCode?: T;
  maps?:
    | T
    | {
        mapName?: T;
        position?: T;
        id?: T;
      };
  teams?:
    | T
    | {
        teamName?: T;
        color?: T;
        players?:
          | T
          | {
              user?: T;
              isReady?: T;
              id?: T;
            };
        completedCells?:
          | T
          | {
              cellPosition?: T;
              completedAt?: T;
              id?: T;
            };
        teamStatus?: T;
        id?: T;
      };
  gameStatus?: T;
  winnerTeam?: T;
  startedAt?: T;
  completedAt?: T;
  duration?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "races_select".
 */
export interface RacesSelect<T extends boolean = true> {
  title?: T;
  isPublic?: T;
  inviteCode?: T;
  category?: T;
  totalRounds?: T;
  currentRound?: T;
  currentMap?: T;
  server?:
    | T
    | {
        ip?: T;
        port?: T;
        name?: T;
      };
  players?:
    | T
    | {
        user?: T;
        ingameNick?: T;
        roundsWon?: T;
        isReady?: T;
        id?: T;
      };
  rounds?:
    | T
    | {
        roundNumber?: T;
        mapName?: T;
        winner?: T;
        finishTime?: T;
        completedAt?: T;
        id?: T;
      };
  winner?: T;
  status?: T;
  botId?: T;
  createdBy?: T;
  startedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bots_select".
 */
export interface BotsSelect<T extends boolean = true> {
  name?: T;
  containerId?: T;
  mode?: T;
  status?: T;
  connectedServer?:
    | T
    | {
        ip?: T;
        port?: T;
        name?: T;
      };
  linkedGame?: T;
  linkedUser?: T;
  logs?:
    | T
    | {
        timestamp?: T;
        level?: T;
        message?: T;
        id?: T;
      };
  startedAt?: T;
  stoppedAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  title?: T;
  message?: T;
  isRead?: T;
  actionUrl?: T;
  relatedGame?: T;
  relatedUser?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "friend-requests_select".
 */
export interface FriendRequestsSelect<T extends boolean = true> {
  sender?: T;
  recipient?: T;
  status?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  coverImage?: T;
  author?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  views?: T;
  likes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-posts_select".
 */
export interface ForumPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  author?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  isPinned?: T;
  views?: T;
  likes?: T;
  replies?:
    | T
    | {
        author?: T;
        content?: T;
        createdAt?: T;
        likes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_select".
 */
export interface SupportSelect<T extends boolean = true> {
  subject?: T;
  category?: T;
  priority?: T;
  status?: T;
  description?: T;
  createdBy?: T;
  contactEmail?: T;
  responses?:
    | T
    | {
        message?: T;
        author?: T;
        isStaffResponse?: T;
        timestamp?: T;
        id?: T;
      };
  attachments?:
    | T
    | {
        file?: T;
        description?: T;
        id?: T;
      };
  metadata?:
    | T
    | {
        requestedName?: T;
        conflictingUser?: T;
      };
  resolvedAt?: T;
  resolutionNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-requests_select".
 */
export interface VerificationRequestsSelect<T extends boolean = true> {
  nickname?: T;
  status?: T;
  message?: T;
  currentServer?: T;
  containerId?: T;
  user?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-sessions_select".
 */
export interface ChatSessionsSelect<T extends boolean = true> {
  initiator?: T;
  target?: T;
  targetNickname?: T;
  status?: T;
  server?:
    | T
    | {
        ip?: T;
        port?: T;
        name?: T;
      };
  botContainerId?: T;
  startedAt?: T;
  endedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions_select".
 */
export interface PushSubscriptionsSelect<T extends boolean = true> {
  user?: T;
  endpoint?: T;
  p256dh?: T;
  auth?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  participants?:
    | T
    | {
        user?: T;
        id?: T;
      };
  lastMessage?: T;
  lastMessageAt?: T;
  lastMessageBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  conversation?: T;
  sender?: T;
  content?: T;
  isRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "in-game-messages_select".
 */
export interface InGameMessagesSelect<T extends boolean = true> {
  session?: T;
  sender?: T;
  content?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-settings".
 */
export interface VerificationSetting {
  id: string;
  /**
   * Servers where /verify command is available
   */
  servers: {
    /**
     * Human-readable name (e.g., "GER Verify #1")
     */
    name: string;
    ip: string;
    port: number;
    /**
     * Server region (e.g., EU, NA, AS)
     */
    region?: string | null;
    id?: string | null;
  }[];
  /**
   * Maximum number of verification bots running simultaneously
   */
  maxConcurrentBots?: number | null;
  /**
   * How long a verification request stays valid (default: 10 minutes)
   */
  verificationTtlMs?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-categories".
 */
export interface CustomCategory {
  id: string;
  categories?:
    | {
        /**
         * Human-readable name (e.g., "EmpaTee Picks")
         */
        name: string;
        /**
         * URL-safe identifier, must start with "custom_" (e.g., "custom_empatee-picks")
         */
        slug: string;
        description?: string | null;
        createdBy?: (string | null) | User;
        maps: {
          mapName: string;
          /**
           * Auto-fetched from DDNet API
           */
          difficulty?: number | null;
          /**
           * Auto-fetched from DDNet API
           */
          points?: number | null;
          /**
           * The DDNet category this map belongs to
           */
          type?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-settings_select".
 */
export interface VerificationSettingsSelect<T extends boolean = true> {
  servers?:
    | T
    | {
        name?: T;
        ip?: T;
        port?: T;
        region?: T;
        id?: T;
      };
  maxConcurrentBots?: T;
  verificationTtlMs?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-categories_select".
 */
export interface CustomCategoriesSelect<T extends boolean = true> {
  categories?:
    | T
    | {
        name?: T;
        slug?: T;
        description?: T;
        createdBy?: T;
        maps?:
          | T
          | {
              mapName?: T;
              difficulty?: T;
              points?: T;
              type?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}